///////////////////////////////////////////////////////////////////////////////
/// @fn parseError
/// @brief Used only on the error page
///////////////////////////////////////////////////////////////////////////////
parse.lineMatch.txt="Error:"
strlen parse.lineMatch.txt,j
substr parse.buffer.txt,parse.eval.txt,0,j
if(parse.eval.txt==parse.lineMatch.txt)
{
  printer.error.txt+=parse.buffer.txt
  printer.error.txt+="\r"
}
