///////////////////////////////////////////////////////////////////////////////
/// @fn luxInitialize 1
/// @brief Sets up the lux framework
///////////////////////////////////////////////////////////////////////////////
// ReturnPage=dp
DiagReturnPage=dp
if(HandleCallback==0)
{
  click luxRunOnce,1
}else
{
  // click luxDoCallback,1
}
// click luxView,1
// click luxAnimate,1
click luxSleep,1
// click luxController,1
// click luxDoCallback,0 //Clears callback vars


///////////////////////////////////////////////////////////////////////////////
/// @fn luxRunOnce
/// @breif Does not run when returning from dialog boxes
///////////////////////////////////////////////////////////////////////////////
tValue.txt=vars.returnVal.txt

//key1 click
tValue+="1"

//Set
vars.returnVal.txt=tValue.txt
HandleCallback=1
page DiagReturnPage

//Close button
vars.returnVal.txt="null"
HandleCallback=0
page DiagReturnPage