Page octoprint
    Attributes
        ID                 : 0
        Scope              : local
        Send Component ID  : disabled
        Opacity            : 127
        Width              : 480
        Effect             : load
        Locked             : no
        Swide up page ID   : disabled
        Swide down page ID : disabled
        Swide left page ID : disabled
        Swide right page ID: disabled
        Fill               : picture
        Back. Picture ID   : 3
    
    Events
        Preinitialize Event
            click luxInit,1
        
        Page Exit Event
            click luxInit,0
        
Text tStop
    Attributes
        ID                      : 20
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 145
        y coordinate            : 223
        Width                   : 80
        Height                  : 25
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 3
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : center
        Vertical Alignment      : center
        Input Type              : character
        Text                    : Stop
        Max. Text Size          : 10
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tAdjustZ
    Attributes
        ID                      : 21
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 350
        y coordinate            : 199
        Width                   : 80
        Height                  : 23
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 3
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : center
        Vertical Alignment      : center
        Input Type              : character
        Text                    : Adjust Z
        Max. Text Size          : 24
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tPrint
    Attributes
        ID                      : 22
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 56
        y coordinate            : 223
        Width                   : 80
        Height                  : 24
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 3
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : center
        Vertical Alignment      : center
        Input Type              : character
        Text                    : Print
        Max. Text Size          : 24
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tPause
    Attributes
        ID                      : 23
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 232
        y coordinate            : 223
        Width                   : 80
        Height                  : 24
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 3
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : center
        Vertical Alignment      : center
        Input Type              : character
        Text                    : Pause
        Max. Text Size          : 24
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tFanSpeed
    Attributes
        ID                      : 27
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 354
        y coordinate            : 6
        Width                   : 60
        Height                  : 16
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 1
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 255
        Max. Text Size          : 7
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            click bFan,1
        
Text tT1Temp
    Attributes
        ID                      : 28
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 130
        y coordinate            : 6
        Width                   : 60
        Height                  : 16
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 1
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 7
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            click bT1,1
        
Text tBedTemp
    Attributes
        ID                      : 29
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 261
        y coordinate            : 6
        Width                   : 60
        Height                  : 16
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 1
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 7
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            click bBed,1
        
Text tT0Temp
    Attributes
        ID                      : 30
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 25
        y coordinate            : 6
        Width                   : 60
        Height                  : 16
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Border Color            : 0
        Border Width            : 2
        Font ID                 : 1
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : top
        Input Type              : character
        Text                    : 
        Max. Text Size          : 7
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tTitle
    Attributes
        ID                      : 37
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 32
        y coordinate            : 32
        Width                   : 258
        Height                  : 43
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 10
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : top
        Input Type              : character
        Text                    : Octoprint Control
        Max. Text Size          : 32
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Picture pOctopus
    Attributes
        ID               : 1
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 127
        y coordinate     : 70
        Width            : 116
        Height           : 93
        Effect           : load
        Picture ID       : 72
    
Button bStop
    Attributes
        ID                                  : 2
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 145
        y coordinate                        : 148
        Width                               : 80
        Height                              : 80
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 11
        Cropped Back. Picture ID (Unpressed): 74
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 73
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 3
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //Stop click
            diagPrompt.tMessage.txt="Stop Print?"
            ReturnVal=1
            ReturnObj=2
            page diagPrompt
        
        Touch Release Event
            //Stop callback
            if(ReturnVal!=-1)
            {
                commands.command.txt="M118 A1 P0 action:cancel"
                click luxSend,1
                commands.command.txt="M524"
                click luxSend,1
            }
        
Button bPause
    Attributes
        ID                                  : 3
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 232
        y coordinate                        : 148
        Width                               : 80
        Height                              : 80
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 11
        Cropped Back. Picture ID (Unpressed): 74
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 73
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 3
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            commands.command.txt="M118 A1 P0 action:pause"
            click luxSend,1
        
Button bPrint
    Attributes
        ID                                  : 4
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 56
        y coordinate                        : 148
        Width                               : 80
        Height                              : 80
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 11
        Cropped Back. Picture ID (Unpressed): 74
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 73
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 3
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            commands.command.txt="M118 A1 P0 action:start"
            click luxSend,1
        
Button bFan
    Attributes
        ID                                  : 5
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 325
        y coordinate                        : 0
        Width                               : 68
        Height                              : 30
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 7
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 7
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bFan click
            ReturnObj=7
            numpad.tCaption.txt="Fan Speed"
            vars.returnVal.txt=""
            page numpad
        
        Touch Release Event
            //bFan callback
            if(vars.returnVal.txt!="null")
            {
                commands.queue.txt+="M106 S"
                commands.queue.txt+=vars.returnVal.txt
                commands.queue.txt+="\r"
                click luxSend,0
            }
        
Button bT0
    Attributes
        ID                                  : 6
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 5
        y coordinate                        : 0
        Width                               : 84
        Height                              : 30
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 8
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 7
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bT0 click
            ReturnObj=8
            numpad.tCaption.txt="T0 Temperature"
            vars.returnVal.txt=""
            page numpad
        
        Touch Release Event
            //bT0 callback
            if(vars.returnVal.txt!="null")
            {
                commands.queue.txt+="M104 T0 S"
                commands.queue.txt+=vars.returnVal.txt
                commands.queue.txt+="\rM105\r"
                click luxSend,0
            }
        
Button bT1
    Attributes
        ID                                  : 7
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 105
        y coordinate                        : 0
        Width                               : 84
        Height                              : 30
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 8
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 7
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bT1 click
            ReturnObj=9
            numpad.tCaption.txt="T1 Temperature"
            vars.returnVal.txt=""
            page numpad
        
        Touch Release Event
            //bT1 callback
            if(vars.returnVal.txt!="null")
            {
                commands.queue.txt+="M104 T1 S"
                commands.queue.txt+=vars.returnVal.txt
                commands.queue.txt+="\rM105\r"
                click luxSend,0
            }
        
Button bBed
    Attributes
        ID                                  : 8
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 212
        y coordinate                        : 0
        Width                               : 84
        Height                              : 30
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 8
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 7
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bBed click
            ReturnObj=10
            numpad.tCaption.txt="Bed Temperature"
            vars.returnVal.txt=""
            page numpad
        
        Touch Release Event
            //bBed callback
            if(vars.returnVal.txt!="null")
            {
                commands.queue.txt+="M140 S"
                commands.queue.txt+=vars.returnVal.txt
                commands.queue.txt+="\rM105\r"
                click luxSend,0
            }
        
Button bClose
    Attributes
        ID                                  : 9
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 435
        y coordinate                        : 0
        Width                               : 45
        Height                              : 41
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 6
        Back. Picture ID (Pressed)          : 40
        Cropped Back. Picture ID (Pressed)  : 5
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            page MAIN
        
Button bStepup
    Attributes
        ID                                  : 10
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 352
        y coordinate                        : 77
        Width                               : 76
        Height                              : 62
        Effect                              : load
        Fill                                : crop image
        Border Color                        : 0
        Border Width                        : 2
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 74
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 73
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 10
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bStepup click
            commands.command.txt="M290 Z0.02"
            click luxSend,1
            commands.command.txt="M500"
            click luxSend,1
        
Button bStepdown
    Attributes
        ID                                  : 11
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 352
        y coordinate                        : 139
        Width                               : 75
        Height                              : 61
        Effect                              : load
        Fill                                : crop image
        Border Color                        : 0
        Border Width                        : 2
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 74
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 73
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 10
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bStepdown click
            commands.command.txt="M290 Z-0.02"
            click luxSend,1
            commands.command.txt="M500"
            click luxSend,1
        
Hotspot luxSpeed
    Attributes
        ID               : 12
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 244
        y coordinate     : 65491
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSpeed 1
            /// @brief Get Speed
            ///////////////////////////////////////////////////////////////////////////////
            commands.queue.txt+="M220\r"
            click luxSend,0
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSpeed 0
            /// @brief Set Speed
            ///////////////////////////////////////////////////////////////////////////////
            commands.queue.txt+="M220 S"
            commands.queue.txt+=vars.returnVal.txt
            commands.queue.txt+="\rM220\r"
            click luxSend,0
        
Hotspot luxFlow
    Attributes
        ID               : 13
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 244
        y coordinate     : 65513
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxFlow 1
            /// @brief Get Flow
            ///////////////////////////////////////////////////////////////////////////////
            commands.queue.txt+="M221\r"
            click luxSend,0
        
Hotspot luxInit
    Attributes
        ID               : 14
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 116
        y coordinate     : 65419
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxInitialize 1
            /// @brief Sets up the lux framework
            ///////////////////////////////////////////////////////////////////////////////
            click luxView,1
            ReturnPage=dp
            DiagReturnPage=dp
            if(HandleCallback==0)
            {
                //  click luxRunOnce,1
            }else
            {
                click luxDoCallback,1
            }
            //click luxView,1
            //click luxAnimate,1
            //click luxSleep,1
            click luxController,1
            click luxDoCallback,0 //Clears callback vars
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxInitialize 0
            /// @brief Call when perminently exiting the page
            ///////////////////////////////////////////////////////////////////////////////
            //click luxSleep,0
        
Hotspot luxDoCallback
    Attributes
        ID               : 15
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65535
        y coordinate     : 65509
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxCallback 1
            /// @brief Control callbacks
            ///////////////////////////////////////////////////////////////////////////////
            if(ReturnObj==0) //Direct to custom controller callback
            {
                click luxController,0
            }else
            {
                click b[ReturnObj],0
            }
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxCallback 0
            /// @brief Clear callback vars
            ///////////////////////////////////////////////////////////////////////////////
            ReturnVal=-1
            vars.returnVal.txt="null"
            HandleCallback=0
            parse.callback.txt="null"
            parse.callbackReturn.txt="null"
        
Hotspot luxController
    Attributes
        ID               : 16
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 116
        y coordinate     : 65465
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxController,1
            /// @brief Program loop
            ///////////////////////////////////////////////////////////////////////////////
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxController,0
            /// @brief Custom on page callback handling
            ///////////////////////////////////////////////////////////////////////////////
        
Hotspot luxNotify
    Attributes
        ID               : 17
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 3
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            click parseCommon,1
            click parseTemp,1
            click parsePrintSet,1
            click serialHistory,1
        
Hotspot luxView
    Attributes
        ID               : 19
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 116
        y coordinate     : 65491
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxView,1
            /// @brief Updates states for controls
            ///////////////////////////////////////////////////////////////////////////////
            click luxControlBar,1
        
Hotspot parseTemp
    Attributes
        ID               : 24
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 55
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            //Qualify Line
            parse.matched.val=0
            parse.lineMatch.txt=" T:"
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                parse.matched.val=1
            }
            parse.lineMatch.txt="ok T:" //Handle M105
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                parse.matched.val=1
                ok=1
            }
            if(parse.matched.val==1)
            {
                //Bed Temp
                spstr parse.buffer.txt,parse.match.txt,"B:",1 //Split by B:
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.bedTemp.val,0,0 //Give bed temp at index 0
                //Bed SetTemp
                spstr parse.buffer.txt,parse.match.txt," /",2
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.setBedTemp.val,0,0 //Give bedSetTemp at index 0
                //T0 Temp
                spstr parse.buffer.txt,parse.match.txt,"T0:",1 //Get second occurance because of Marlin active extruder temperature reporting bug
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.T0Temp.val,0,0
                //T0 SetTemp
                spstr parse.buffer.txt,parse.match.txt," /",3
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.T0SetTemp.val,0,0 //Give bedSetTemp at index 0
                //T1 Temp
                spstr parse.buffer.txt,parse.match.txt,"T1:",1
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.T1Temp.val,0,0
                //T1 SetTemp
                spstr parse.buffer.txt,parse.match.txt," /",4
                spstr parse.match.txt,vars.s.txt," ",0 //Split substring by space
                covx vars.s.txt,printer.T1SetTemp.val,0,0 //Give bedSetTemp at index 0
            }
        
Hotspot luxControlBar
    Attributes
        ID               : 25
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 373
        y coordinate     : 65512
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxControlBar 1
            /// @brief Update temperature text
            ///////////////////////////////////////////////////////////////////////////////
            covx printer.T0Temp.val,vars.s.txt,0,0 //Update T0
            tT0Temp.txt=vars.s.txt
            tT0Temp.txt+="/"
            covx printer.T0SetTemp.val,vars.s.txt,0,0
            tT0Temp.txt+=vars.s.txt
            covx printer.T1Temp.val,vars.s.txt,0,0 //Update T1
            tT1Temp.txt=vars.s.txt
            tT1Temp.txt+="/"
            covx printer.T1SetTemp.val,vars.s.txt,0,0
            tT1Temp.txt+=vars.s.txt
            covx printer.bedTemp.val,vars.s.txt,0,0 //Update Bed
            tBedTemp.txt=vars.s.txt
            tBedTemp.txt+="/"
            covx printer.setBedTemp.val,vars.s.txt,0,0
            tBedTemp.txt+=vars.s.txt
            covx printer.fanSpeed.val,vars.s.txt,0,0 //Fan Speed
            tFanSpeed.txt=vars.s.txt
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            // @fn luxControlBar 0
            // @brief Animate control bar
            ///////////////////////////////////////////////////////////////////////////////
            if(printer.T0SetTemp.val!=0) //T0 Temp
            {
                if(printer.T0Temp.val<printer.T0SetTemp.val) //Heating
                {
                    bT0.picc=bT0.picc2+Frame
                }else
                {
                    bT0.picc=bT0.picc2 //Temperature reached
                }
            }else //Cooling
            {
                bT0.picc=bT0.picc2+1
            }
            if(printer.T1SetTemp.val!=0) //T1 Temp
            {
                if(printer.T1Temp.val<printer.T1SetTemp.val) //Heating
                {
                    bT1.picc=bT1.picc2+Frame
                }else
                {
                    bT1.picc=bT1.picc2 //Temperature reached
                }
            }else //Cooling
            {
                bT1.picc=bT1.picc2+1
            }
            if(printer.setBedTemp.val!=0) //Bed Temp
            {
                if(printer.bedTemp.val<printer.setBedTemp.val) //Heating
                {
                    bBed.picc=bBed.picc2+Frame
                }else
                {
                    bBed.picc=bBed.picc2 //Temperature reached
                }
            }else //Cooling
            {
                bBed.picc=bBed.picc2+1
            }
            if(printer.fanSpeed.val>0) //Fan
            {
                bFan.picc=bFan.picc2+FrameB //picc2 use to signify starting frame
            }
        
Hotspot parsePrintSet
    Attributes
        ID               : 31
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 81
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            // Feed Rate / Speed
            // FR:100%
            parse.lineMatch.txt="FR:" //Qualify Line
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,vars.s.txt,":",1
                spstr vars.s.txt,vars.s2.txt,"%",0
                covx vars.s2.txt,printer.speed.val,0,0
            }
            // Flow
            // echo:E0 Flow: 100%
            parse.lineMatch.txt=" Flow: " //Qualify Line
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,7,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,vars.s.txt," ",2
                spstr vars.s.txt,vars.s2.txt,"%",0
                covx vars.s2.txt,printer.flow.val,0,0
            }
        
Hotspot luxRead
    Attributes
        ID               : 32
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65535
        y coordinate     : 65462
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxRead 1
            /// @brief Read the buffer and notify when end of line is reached
            ///////////////////////////////////////////////////////////////////////////////
            if(usize>0)
            {
                while(SerialPos<usize)
                {
                    ucopy parse.startChar.txt,SerialPos,1,0 //Check next character
                    if(u[SerialPos]==10||u[SerialPos]==13) //If linefeed or carriage return
                    {
                        //EOL reached
                        strlen parse.buffer.txt,BufferLen //Record buffer length
                        click luxNotify,1 //Notify listeners
                        parse.buffer.txt="" //Clear buffer
                    }
                    if(u[SerialPos]==13) //Cariage return
                    {
                        SerialPos++       //Lookahead to next char
                        if(SerialPos<usize) //If under buffersize
                        {
                            if(u[SerialPos]!=10) //But no linefeed
                            {
                                SerialPos-- //Rollback
                            }
                        }else
                        {
                            SerialPos-- //Rollback if over buffersize
                        }
                    }else
                    {
                        if(u[SerialPos]!=10) //Add character to line if not CR or LF
                        {
                            parse.buffer.txt+=parse.startChar.txt
                        }
                    }
                    SerialPos++ //Next character
                }
                if(SerialPos==usize) //End of buffer reached
                {
                    code_c
                    BufferLen=0
                    SerialPos=0
                }
            }
        
Hotspot luxSend
    Attributes
        ID               : 33
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65535
        y coordinate     : 65437
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSend 1
            /// @brief Send a single command
            /// @param[in] command.command.txt
            ///////////////////////////////////////////////////////////////////////////////
            prints commands.command.txt,0
            printh 0A
            ok=0
            click serialHistory,0
            commands.command.txt=""
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSend 0
            /// @brief Send command queue, waiting for ok between each command
            /// @brief Waits a max of 10 times for each ok
            ///////////////////////////////////////////////////////////////////////////////
            strlen commands.queue.txt,QueueLen //get the length of the command queue
            if(ok==1&&busy==0) //Send Queue
            {
                QueueBlocks=0
                while(QueueLen>0&&QueueBlocks<=10)
                {
                    click luxRead,1
                    if(ok==1&&busy==0)
                    {
                        spstr commands.queue.txt,vars.s.txt,"\r",0
                        if(vars.s.txt!="")
                        {
                            strlen vars.s.txt,CommandLen //get the lenght of the command
                            CharLen=QueueLen-CommandLen //calc the amount of chars to copy
                            //remove the command from the queue by getting a substring of the commandqueue
                            substr commands.queue.txt,commands.queue.txt,CommandLen+2,CharLen //+2 to count \r
                            commands.command.txt=vars.s.txt
                            click luxSend,1
                        }else
                        {
                            commands.queue.txt=""
                            QueueLen=0
                        }
                    }else
                    {
                        QueueBlocks+=1
                    }
                    strlen commands.queue.txt,QueueLen //Refresh the command queue lenght
                }
            }
        
Hotspot parseCommon
    Attributes
        ID               : 34
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 29
        Width            : 106
        Height           : 16
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn     parseCommon 1
            /// @brief  Essential items to be parsed
            ///////////////////////////////////////////////////////////////////////////////
            parse.lineMatch.txt="//action:paused filament_runout"
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                printer.filamentRunout.val=1
                printer.paused.val=1
                parse.buffer.txt=""
                if(dp!=PAUSE_PAGE)
                {
                    page PAUSE_PAGE
                }
            }
            parse.lineMatch.txt="//action:resumed"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                printer.filamentRunout.val=0
                printer.paused.val=0
            }
            parse.lineMatch.txt="echo:busy: paused for user"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                printer.paused.val=1
                parse.buffer.txt=""
                if(dp!=PAUSE_PAGE)
                {
                    page PAUSE_PAGE
                }
            }
            parse.lineMatch.txt=" External Reset" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ExternalReset=1
            }
            parse.lineMatch.txt="start"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                ExternalReset=1
            }
            parse.lineMatch.txt="//lux:power_pin" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ShutDown=1
            }
            parse.lineMatch.txt="echo://lux:power_pin" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ShutDown=1
            }
            parse.lineMatch.txt="ok" //Ok
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="ok T:" //M105 ok
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="ok " //Advanced ok
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="echo:busy: processing" //Busy
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                busy=1
            }else
            {
                commands.linesNotBusy.val+=1
                if(commands.linesNotBusy.val>=5)
                {
                    busy=0
                    commands.linesNotBusy.val=0
                }
            }
            parse.lineMatch.txt="Active Extruder: " //Active Extruder
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.match.txt,"Active Extruder: ",1
                covx parse.match.txt,j,0,0
                Tool=j
            }
            parse.lineMatch.txt="M106 P0 S" //Fan
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.match.txt,"M106 P0 S",1
                covx parse.match.txt,printer.fanSpeed.val,0,0
            }
            parse.lineMatch.txt="//lux:callback " //Serial callback
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.callbackReturn.txt,parse.lineMatch.txt,1
            }
            parse.lineMatch.txt="//lux:M117 " //M117
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,printer.m117.txt,parse.lineMatch.txt,1
            }
            parse.lineMatch.txt="Error:" //Error
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                printer.error.txt=parse.buffer.txt
                printer.error.txt+="\r"
                parse.buffer.txt=""
                Error=1
            }
            if(ShutDown==1)
            {
                ShutDown=0
                page shutdown
            }
            if(Error==1)
            {
                Error=0
                page ERROR_PAGE
            }
            if(ExternalReset==1)
            {
                ExternalReset=0
                parse.buffer.txt=""
                BufferLen=0
                code_c
                page connect
            }
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn         parseCommon 0
            ///
            /// @brief      Parse buffer using a starting and ending position
            /// @param[in]  parse.search.txt      Text to search for
            /// @param[in]  parse.startPos.val    Starting char postion to search from
            /// @param[out] parse.matched.val     1 if match, 0 if no match
            ///////////////////////////////////////////////////////////////////////////////
            parse.matched.val=0
            parse.eval.txt=parse.buffer.txt
            strlen parse.search.txt,j
            substr parse.eval.txt,parse.result.txt,parse.startPos.val,j
            if(parse.result.txt==parse.search.txt)
            {
                parse.matched.val=1
            }else
            {
                parse.matched.val=0
            }
        
Hotspot serialHistory
    Attributes
        ID               : 35
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 107
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn serialHistory 1
            /// @brief Preserves command recieved history
            ///////////////////////////////////////////////////////////////////////////////
            click historyFilters,1
            parse.last.txt=parse.buffer.txt
            if(parse.last.txt!="")
            {
                strlen parse.last.txt,BuffHistNewLineLen
                strlen connect.history.txt,BuffHistLen
                BuffHistNewLen=BuffHistLen+BuffHistNewLineLen
                if(BuffHistNewLen>=connect.history.txt_maxl) //Check if reached buffer lenght
                {
                    //Cut lenght of new command out of buffer
                    substr connect.history.txt,vars.slarge.txt,BuffHistNewLineLen,connect.history.txt_maxl
                    connect.history.txt=vars.slarge.txt
                    //Find length until next \r
                    spstr connect.history.txt,vars.slarge.txt,"\r",0
                    strlen vars.slarge.txt,BuffHistTrimLen
                    BuffHistTrimLen+=1 // Trim one more char
                    //Cut that out of the rest of the buffer
                    strlen connect.history.txt,BuffHistLen //Get new buffer len
                    substr connect.history.txt,vars.slarge.txt,BuffHistTrimLen+1,BuffHistLen-BuffHistTrimLen //+1 is to advance cursor
                    connect.history.txt=vars.slarge.txt
                }
                //connect.history.txt+="R: "
                connect.history.txt+=parse.last.txt
                connect.history.txt+="\r"
            }
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn serialHistory 0
            /// @brief Preserves command sent history
            ///////////////////////////////////////////////////////////////////////////////
            // Scroll up command history
            commands.last.txt=commands.command.txt
            strlen commands.last.txt,BuffHistNewLineLen
            strlen connect.history.txt,BuffHistLen
            BuffHistNewLen=BuffHistLen+BuffHistNewLineLen
            if(BuffHistNewLen>=connect.history.txt_maxl) //Check if reached buffer lenght
            {
                //Cut lenght of new command out of buffer
                substr connect.history.txt,vars.slarge.txt,BuffHistNewLineLen,connect.history.txt_maxl
                connect.history.txt=vars.slarge.txt
                //Find length until next \r
                spstr connect.history.txt,vars.slarge.txt,"\r",0
                strlen vars.slarge.txt,BuffHistTrimLen
                BuffHistTrimLen+=1 // Trim one more char
                //Cut that out of the rest of the buffer
                strlen connect.history.txt,BuffHistLen //Get new buffer len
                substr connect.history.txt,vars.slarge.txt,BuffHistTrimLen+1,BuffHistLen-BuffHistTrimLen //+1 is to advance cursor
                connect.history.txt=vars.slarge.txt
            }
            connect.history.txt+="S: "
            connect.history.txt+=commands.last.txt
            connect.history.txt+="\r"
        
Hotspot historyFilters
    Attributes
        ID               : 36
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 488
        y coordinate     : 133
        Width            : 106
        Height           : 16
        Effect           : load
    
    Events
        Touch Press Event
            //Qualify Line
            parse.matched.val=0
            if(historyFilters.swTemp.val==1)
            {
                parse.lineMatch.txt=" T:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
                parse.lineMatch.txt="ok T:" //Handle M105 Temp Response
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swBusy.val==1)
            {
                parse.lineMatch.txt="echo:busy: processing" //Busy
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swSDCard.val==1)
            {
                parse.lineMatch.txt="Not SD printing" //SD Status
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
                parse.lineMatch.txt="SD printing byte " //SD Progress
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swEcho.val==1)
            {
                parse.lineMatch.txt="echo:echo:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    spstr parse.buffer.txt,parse.buffer.txt,"echo:",2
                }
            }
            if(historyFilters.swEcho.val==1)
            {
                parse.lineMatch.txt="echo:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    spstr parse.buffer.txt,parse.buffer.txt,"echo:",1
                }
            }
            parse.lineMatch.txt="X:"
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                parse.matched.val=1
            }
            if(parse.matched.val==1)
            {
                parse.buffer.txt=""
                parse.matched.val=0
            }
        
Timer luxRun
    Attributes
        ID         : 18
        Scope      : local
        Period (ms): 100
        Enabled    : yes
    
    Events
        Timer Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxRun
            /// @breif Main Program Loop
            ///////////////////////////////////////////////////////////////////////////////
            click luxRead,1
            click luxView,1
            click luxController,1
            click luxSend,0
        
Timer luxAnimate
    Attributes
        ID         : 26
        Scope      : local
        Period (ms): 2000
        Enabled    : yes
    
    Events
        Timer Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxAnimate
            /// @brief Animation Loop
            ///////////////////////////////////////////////////////////////////////////////
            Frame=Frame^1 //Toggle Frame between 0 and 1
            if(FrameB<3)
            {
                FrameB+=1
            }else
            {
                FrameB=0
            }
            click luxControlBar,0
        
