Page sdPrint
    Attributes
        ID                 : 0
        Scope              : local
        Send Component ID  : disabled
        Opacity            : 127
        Width              : 1024
        Effect             : load
        Locked             : no
        Swide up page ID   : disabled
        Swide down page ID : disabled
        Swide left page ID : disabled
        Swide right page ID: disabled
        Fill               : picture
        Back. Picture ID   : 3
    
    Events
        Preinitialize Event
            click luxInit,1
        
        Page Exit Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn onExit
            ///////////////////////////////////////////////////////////////////////////////
            click luxInit,0
        
Variable (string) state
    Attributes
        ID            : 16
        Scope         : local
        Text          : null
        Max. Text Size: 16
    
Variable (int32) page
    Attributes
        ID   : 19
        Scope: local
        Value: 0
    
Variable (int32) gettingFiles
    Attributes
        ID   : 20
        Scope: local
        Value: 0
    
Variable (int32) selectedIndex
    Attributes
        ID   : 21
        Scope: local
        Value: 4294967295
    
Variable (string) selectedFile
    Attributes
        ID            : 22
        Scope         : local
        Text          : 
        Max. Text Size: 128
    
Text f0
    Attributes
        ID                      : 2
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 33
        y coordinate            : 62
        Width                   : 329
        Height                  : 35
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 6
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 254
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            /// @brief Executed when clicking on a file name
            selectedIndex.val=0
            click selectFile,1
        
Text f4
    Attributes
        ID                      : 3
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 33
        y coordinate            : 210
        Width                   : 329
        Height                  : 35
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 6
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 254
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            /// @brief Executed when clicking on a file name
            selectedIndex.val=4
            click selectFile,1
        
Text f3
    Attributes
        ID                      : 4
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 33
        y coordinate            : 173
        Width                   : 329
        Height                  : 35
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 6
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 254
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            /// @brief Executed when clicking on a file name
            selectedIndex.val=3
            click selectFile,1
        
Text f1
    Attributes
        ID                      : 5
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 33
        y coordinate            : 99
        Width                   : 329
        Height                  : 35
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 6
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 254
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            /// @brief Executed when clicking on a file name
            selectedIndex.val=1
            click selectFile,1
        
Text tMessage
    Attributes
        ID                      : 6
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 77
        y coordinate            : 139
        Width                   : 207
        Height                  : 30
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 7
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : center
        Vertical Alignment      : center
        Input Type              : character
        Text                    : Message
        Max. Text Size          : 36
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tTitle
    Attributes
        ID                      : 9
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 20
        y coordinate            : 20
        Width                   : 253
        Height                  : 31
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 10
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : top
        Input Type              : character
        Text                    : Choose File
        Max. Text Size          : 16
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
Text tFiles
    Attributes
        ID                  : 15
        Scope               : local
        Dragging            : 0
        Send Component ID   : disabled
        Opacity             : 127
        x coordinate        : 544
        y coordinate        : 13
        Width               : 447
        Height              : 566
        Effect              : load
        Fill                : solid color
        Style               : flat
        Associated Keyboard : none
        Font ID             : 0
        Back. Color         : 65535
        Font Color          : 0
        Horizontal Alignment: left
        Vertical Alignment  : top
        Input Type          : character
        Text                : 
        Max. Text Size      : 57599
        Word wrap           : enabled
        Horizontal Spacing  : 0
        Vertical Spacing    : 0
    
Text f2
    Attributes
        ID                      : 23
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 33
        y coordinate            : 138
        Width                   : 329
        Height                  : 35
        Effect                  : load
        Fill                    : crop image
        Associated Keyboard     : none
        Font ID                 : 6
        Cropped Back. Picture ID: 0
        Horizontal Alignment    : left
        Vertical Alignment      : center
        Input Type              : character
        Text                    : 
        Max. Text Size          : 254
        Word wrap               : disabled
        Horizontal Spacing      : 0
        Vertical Spacing        : 0
    
    Events
        Touch Press Event
            /// @brief Executed when clicking on a file name
            selectedIndex.val=2
            click selectFile,1
        
Crop Picture pState
    Attributes
        ID                      : 1
        Scope                   : local
        Dragging                : 0
        Send Component ID       : disabled
        Opacity                 : 127
        x coordinate            : 0
        y coordinate            : 0
        Width                   : 373
        Height                  : 272
        Effect                  : load
        Cropped Back. Picture ID: 50
    
Button bPrint
    Attributes
        ID                                  : 8
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 373
        y coordinate                        : 109
        Width                               : 88
        Height                              : 88
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 50
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 49
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bPrint
            print.fileName.txt=selectedFile.txt
            printer.sdPrinting.val=0
            printer.printState.txt="null"
            page print
        
Button bClose
    Attributes
        ID                                  : 11
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 435
        y coordinate                        : 0
        Width                               : 45
        Height                              : 41
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 6
        Back. Picture ID (Pressed)          : 40
        Cropped Back. Picture ID (Pressed)  : 5
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 10
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn bClose
            ///////////////////////////////////////////////////////////////////////////////
            page ReturnPage
        
Button bUp
    Attributes
        ID                                  : 29
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 306
        y coordinate                        : 52
        Width                               : 51
        Height                              : 52
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 51
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 49
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bUp
            bUp.picc=bUp.picc2
            tsw bUp,0
            tsw bDown,0
            if(page.val>0)
            {
                selectedFile.txt=""
                selectedIndex.val=-1
                page.val-=1
                //  click luxGetLong,1
            }
            click selectFile,1
        
Button bDown
    Attributes
        ID                                  : 30
        Scope                               : local
        Dragging                            : 0
        Send Component ID                   : disabled
        Opacity                             : 127
        x coordinate                        : 306
        y coordinate                        : 202
        Width                               : 51
        Height                              : 52
        Effect                              : load
        Fill                                : crop image
        Font ID                             : 1
        Cropped Back. Picture ID (Unpressed): 51
        Back. Picture ID (Pressed)          : 65535
        Cropped Back. Picture ID (Pressed)  : 49
        Horizontal Alignment                : center
        Vertical Alignment                  : center
        State                               : unpressed
        Text                                : 
        Max. Text Size                      : 0
        Word wrap                           : disabled
        Horizontal Spacing                  : 0
        Vertical Spacing                    : 0
    
    Events
        Touch Press Event
            //bDown
            tsw bUp,0
            tsw bDown,0
            bDown.picc=bDown.picc2
            selectedFile.txt=""
            selectedIndex.val=-1
            page.val+=1
            //click luxGetLong,1
            click selectFile,1
        
Hotspot selectFile
    Attributes
        ID               : 7
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 373
        y coordinate     : 65512
        Width            : 106
        Height           : 16
        Effect           : load
    
    Events
        Touch Press Event
            //selectFile
            if(selectedIndex.val>=0)
            {
                k=page.val
                k*=5
                k+=selectedIndex.val
                spstr tFiles.txt,vars.s.txt,"\r",k
                selectedFile.txt=vars.s.txt
            }else
            {
                selectedFile.txt=""
            }
            click luxView,1
        
Hotspot parseFiles
    Attributes
        ID               : 10
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65418
        y coordinate     : 45
        Width            : 106
        Height           : 15
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn parseFiles,1
            ///
            /// @brief Parse filenames and long file names
            ///////////////////////////////////////////////////////////////////////////////
            parse.lineMatch.txt="End file list"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                gettingFiles.val=0 //Getting file state is off, do not listen for filenames
                state.txt="ready"
            }
            if(gettingFiles.val==1)  //Parse filenames
            {
                spstr parse.buffer.txt,vars.s.txt,".gcode",0
                vars.s.txt+=".gcode"
                tFiles.txt+=vars.s.txt
                tFiles.txt+="\r"
            }
            parse.lineMatch.txt="!! Unable to get file list"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                state.txt="no-sd"
            }
            parse.lineMatch.txt="Begin file list"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                tFiles.txt="" //Clear existing file list
                gettingFiles.val=1
                page.val=0
            }
        
Hotspot luxController
    Attributes
        ID               : 12
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 113
        y coordinate     : 65489
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxController,1
            ///
            /// @brief Program loop
            /// @brief state.txts: null, getting-files, ready, no-sd
            ///////////////////////////////////////////////////////////////////////////////
            if(state.txt=="null")
            {
                commands.queue.txt+="M20"
                click luxSend,0
                state.txt="getting-files"
            }
            if(state.txt=="no-sd")
            {
                DiagReturnPage=MAIN
                diagConfirm.tMessage.txt="Unable to get file list"
                page diagConfirm
            }
        
Hotspot luxNotify
    Attributes
        ID               : 13
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65418
        y coordinate     : 14
        Width            : 106
        Height           : 16
        Effect           : load
    
    Events
        Touch Press Event
            click parseCommon,1
            click parseFiles,1
            click serialHistory,1
        
Hotspot luxView
    Attributes
        ID               : 14
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 113
        y coordinate     : 65511
        Width            : 106
        Height           : 15
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxView,1
            ///
            /// @brief Updates states for controls
            ///////////////////////////////////////////////////////////////////////////////
            if(state.txt=="null")
            {
                tMessage.aph=0
                setlayer bUp,0
                setlayer bDown,0
                tsw f0,0
                tsw f1,0
                tsw f2,0
                tsw f3,0
                tsw f4,0
            }
            if(state.txt=="getting-files")
            {
                tMessage.txt="Getting Files"
                tMessage.aph=127
            }
            if(selectedFile.txt=="") //Hide or Show Print button
            {
                tsw bPrint,0
                bPrint.aph=0
            }else
            {
                tsw bPrint,1
                bPrint.aph=127
            }
            if(state.txt=="ready")
            {
                tMessage.aph=0
                tsw f0,1
                tsw f1,1
                tsw f2,1
                tsw f3,1
                tsw f4,1
                strlen tFiles.txt,j //Load file controls
                if(j>0)
                {
                    if(page.val==0) //Button visibility
                    {
                        setlayer bUp,0
                    }else
                    {
                        setlayer bUp,254
                    }
                    spstr tFiles.txt,vars.s.txt,"\r",page.val+1*5 //Check for last page
                    if(vars.s.txt=="")
                    {
                        setlayer bDown,0
                    }else
                    {
                        setlayer bDown,254
                    }
                    bUp.picc=bUp.picc2+2
                    bDown.picc=bDown.picc2+2
                    tsw bUp,1
                    tsw bDown,1
                    k=page.val
                    k*=5
                    spstr tFiles.txt,f0.txt,"\r",k
                    k+=1
                    spstr tFiles.txt,f1.txt,"\r",k
                    k+=1
                    spstr tFiles.txt,f2.txt,"\r",k
                    k+=1
                    spstr tFiles.txt,f3.txt,"\r",k
                    k+=1
                    spstr tFiles.txt,f4.txt,"\r",k
                    for(j=0;j<=45;j++) //Button Group, yellow highlight
                    {
                        if(b[j].type==116&&b[j].txt_maxl==254) //If filetext box
                        {
                            if(b[j].txt==selectedFile.txt)
                            {
                                b[j].pco=65504
                            }else
                            {
                                b[j].pco=65535
                            }
                        }
                    }
                }
            }
        
Hotspot luxInit
    Attributes
        ID               : 17
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 113
        y coordinate     : 65467
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            /////////////////////////////////////////////////////////////////////////////
            /// @fn luxInit 1
            /// @brief Sets up the lux framework
            ///////////////////////////////////////////////////////////////////////////////
            click luxView,1
            //click luxAnimate,1
            click luxController,1
            if(HandleCallback==0)
            {
                //  click luxDoCallback,0 //Clears callback vars
                //  click luxRunOnce,1
            }else
            {
                //  click luxDoCallback,1
                //  click luxDoCallback,0
            }
            // ReturnPage=dp
            DiagReturnPage=dp
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxInitialize 0
            /// @brief Should run on any close button
            ///////////////////////////////////////////////////////////////////////////////
            commands.queue.txt+="M155 S5\r" //Temp auto report on
            click luxSend,0
        
Hotspot luxRead
    Attributes
        ID               : 24
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65535
        y coordinate     : 65462
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxRead 1
            /// @brief Read the buffer and notify when end of line is reached
            ///////////////////////////////////////////////////////////////////////////////
            if(usize>0)
            {
                while(SerialPos<usize)
                {
                    ucopy parse.startChar.txt,SerialPos,1,0 //Check next character
                    if(u[SerialPos]==10||u[SerialPos]==13) //If linefeed or carriage return
                    {
                        //EOL reached
                        strlen parse.buffer.txt,BufferLen //Record buffer length
                        click luxNotify,1 //Notify listeners
                        parse.buffer.txt="" //Clear buffer
                    }
                    if(u[SerialPos]==13) //Cariage return
                    {
                        SerialPos++       //Lookahead to next char
                        if(SerialPos<usize) //If under buffersize
                        {
                            if(u[SerialPos]!=10) //But no linefeed
                            {
                                SerialPos-- //Rollback
                            }
                        }else
                        {
                            SerialPos-- //Rollback if over buffersize
                        }
                    }else
                    {
                        if(u[SerialPos]!=10) //Add character to line if not CR or LF
                        {
                            parse.buffer.txt+=parse.startChar.txt
                        }
                    }
                    SerialPos++ //Next character
                }
                if(SerialPos==usize) //End of buffer reached
                {
                    code_c
                    BufferLen=0
                    SerialPos=0
                }
            }
        
Hotspot luxSend
    Attributes
        ID               : 25
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65535
        y coordinate     : 65437
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSend 1
            /// @brief Send a single command
            /// @param[in] command.command.txt
            ///////////////////////////////////////////////////////////////////////////////
            prints commands.command.txt,0
            printh 0A
            ok=0
            click serialHistory,0
            commands.command.txt=""
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxSend 0
            /// @brief Send command queue, waiting for ok between each command
            /// @brief Waits a max of 10 times for each ok
            ///////////////////////////////////////////////////////////////////////////////
            strlen commands.queue.txt,QueueLen //get the length of the command queue
            if(ok==1&&busy==0) //Send Queue
            {
                QueueBlocks=0
                while(QueueLen>0&&QueueBlocks<=10)
                {
                    click luxRead,1
                    if(ok==1&&busy==0)
                    {
                        spstr commands.queue.txt,vars.s.txt,"\r",0
                        if(vars.s.txt!="")
                        {
                            strlen vars.s.txt,CommandLen //get the lenght of the command
                            CharLen=QueueLen-CommandLen //calc the amount of chars to copy
                            //remove the command from the queue by getting a substring of the commandqueue
                            substr commands.queue.txt,commands.queue.txt,CommandLen+2,CharLen //+2 to count \r
                            commands.command.txt=vars.s.txt
                            click luxSend,1
                        }else
                        {
                            commands.queue.txt=""
                            QueueLen=0
                        }
                    }else
                    {
                        QueueBlocks+=1
                    }
                    strlen commands.queue.txt,QueueLen //Refresh the command queue lenght
                }
            }
        
Hotspot serialHistory
    Attributes
        ID               : 26
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65418
        y coordinate     : 107
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn serialHistory 1
            /// @brief Preserves command recieved history
            ///////////////////////////////////////////////////////////////////////////////
            click historyFilters,1
            parse.last.txt=parse.buffer.txt
            if(parse.last.txt!="")
            {
                strlen parse.last.txt,BuffHistNewLineLen
                strlen connect.history.txt,BuffHistLen
                BuffHistNewLen=BuffHistLen+BuffHistNewLineLen
                if(BuffHistNewLen>=connect.history.txt_maxl) //Check if reached buffer lenght
                {
                    //Cut lenght of new command out of buffer
                    substr connect.history.txt,vars.slarge.txt,BuffHistNewLineLen,connect.history.txt_maxl
                    connect.history.txt=vars.slarge.txt
                    //Find length until next \r
                    spstr connect.history.txt,vars.slarge.txt,"\r",0
                    strlen vars.slarge.txt,BuffHistTrimLen
                    BuffHistTrimLen+=1 // Trim one more char
                    //Cut that out of the rest of the buffer
                    strlen connect.history.txt,BuffHistLen //Get new buffer len
                    substr connect.history.txt,vars.slarge.txt,BuffHistTrimLen+1,BuffHistLen-BuffHistTrimLen //+1 is to advance cursor
                    connect.history.txt=vars.slarge.txt
                }
                //connect.history.txt+="R: "
                connect.history.txt+=parse.last.txt
                connect.history.txt+="\r"
            }
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn serialHistory 0
            /// @brief Preserves command sent history
            ///////////////////////////////////////////////////////////////////////////////
            // Scroll up command history
            commands.last.txt=commands.command.txt
            strlen commands.last.txt,BuffHistNewLineLen
            strlen connect.history.txt,BuffHistLen
            BuffHistNewLen=BuffHistLen+BuffHistNewLineLen
            if(BuffHistNewLen>=connect.history.txt_maxl) //Check if reached buffer lenght
            {
                //Cut lenght of new command out of buffer
                substr connect.history.txt,vars.slarge.txt,BuffHistNewLineLen,connect.history.txt_maxl
                connect.history.txt=vars.slarge.txt
                //Find length until next \r
                spstr connect.history.txt,vars.slarge.txt,"\r",0
                strlen vars.slarge.txt,BuffHistTrimLen
                BuffHistTrimLen+=1 // Trim one more char
                //Cut that out of the rest of the buffer
                strlen connect.history.txt,BuffHistLen //Get new buffer len
                substr connect.history.txt,vars.slarge.txt,BuffHistTrimLen+1,BuffHistLen-BuffHistTrimLen //+1 is to advance cursor
                connect.history.txt=vars.slarge.txt
            }
            connect.history.txt+="S: "
            connect.history.txt+=commands.last.txt
            connect.history.txt+="\r"
        
Hotspot historyFilters
    Attributes
        ID               : 27
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65418
        y coordinate     : 139
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            //Qualify Line
            parse.matched.val=0
            if(historyFilters.swTemp.val==1)
            {
                parse.lineMatch.txt=" T:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
                parse.lineMatch.txt="ok T:" //Handle M105 Temp Response
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swBusy.val==1)
            {
                parse.lineMatch.txt="echo:busy: processing" //Busy
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swSDCard.val==1)
            {
                parse.lineMatch.txt="Not SD printing" //SD Status
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
                parse.lineMatch.txt="SD printing byte " //SD Progress
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    parse.matched.val=1
                }
            }
            if(historyFilters.swEcho.val==1)
            {
                parse.lineMatch.txt="echo:echo:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    spstr parse.buffer.txt,parse.buffer.txt,"echo:",2
                }
            }
            if(historyFilters.swEcho.val==1)
            {
                parse.lineMatch.txt="echo:"
                strlen parse.lineMatch.txt,j
                substr parse.buffer.txt,parse.eval.txt,0,j
                if(parse.eval.txt==parse.lineMatch.txt)
                {
                    spstr parse.buffer.txt,parse.buffer.txt,"echo:",1
                }
            }
            parse.lineMatch.txt="X:"
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                parse.matched.val=1
            }
            if(parse.matched.val==1)
            {
                parse.buffer.txt=""
                parse.matched.val=0
            }
        
Hotspot parseCommon
    Attributes
        ID               : 28
        Scope            : local
        Dragging         : 0
        Send Component ID: disabled
        Opacity          : 127
        x coordinate     : 65418
        y coordinate     : 75
        Width            : 106
        Height           : 17
        Effect           : load
    
    Events
        Touch Press Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn     parseCommon 1
            /// @brief  Essential items to be parsed
            ///////////////////////////////////////////////////////////////////////////////
            parse.lineMatch.txt="// action:paused filament_runout"
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                printer.filamentRunout.val=1
                printer.paused.val=1
                parse.buffer.txt=""
                if(dp!=PAUSE_PAGE)
                {
                    page PAUSE_PAGE
                }
            }
            parse.lineMatch.txt="// action:resumed"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                printer.filamentRunout.val=0
                printer.paused.val=0
            }
            parse.lineMatch.txt="echo:busy: paused for user"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                printer.paused.val=1
                parse.buffer.txt=""
                if(dp!=PAUSE_PAGE)
                {
                    page PAUSE_PAGE
                }
            }
            parse.lineMatch.txt=" External Reset" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ExternalReset=1
            }
            parse.lineMatch.txt="start"
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                ExternalReset=1
            }
            parse.lineMatch.txt="// lux:power_pin" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ShutDown=1
            }
            parse.lineMatch.txt="echo://lux:power_pin" //Shutdown
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt) //This one only works when using substring for some reason
            {
                ShutDown=1
            }
            parse.lineMatch.txt="ok" //Ok
            if(parse.buffer.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="ok T:" //M105 ok
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="ok " //Advanced ok
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                ok=1
                busy=0
            }
            parse.lineMatch.txt="echo:busy: processing" //Busy
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                busy=1
            }else
            {
                commands.linesNotBusy.val+=1
                if(commands.linesNotBusy.val>=5)
                {
                    busy=0
                    commands.linesNotBusy.val=0
                }
            }
            parse.lineMatch.txt="Active Extruder: " //Active Extruder
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.match.txt,"Active Extruder: ",1
                covx parse.match.txt,j,0,0
                Tool=j
            }
            parse.lineMatch.txt="M106 P0 S" //Fan
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.match.txt,"M106 P0 S",1
                covx parse.match.txt,printer.fanSpeed.val,0,0
            }
            parse.lineMatch.txt="// lux:callback " //Serial callback
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,parse.callbackReturn.txt,parse.lineMatch.txt,1
            }
            parse.lineMatch.txt="// lux:M117 " //M117
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                spstr parse.buffer.txt,printer.m117.txt,parse.lineMatch.txt,1
            }
            parse.lineMatch.txt="Error:" //Error
            strlen parse.lineMatch.txt,j
            substr parse.buffer.txt,parse.eval.txt,0,j
            if(parse.eval.txt==parse.lineMatch.txt)
            {
                printer.error.txt=parse.buffer.txt
                printer.error.txt+="\r"
                parse.buffer.txt=""
                Error=1
            }
            if(ShutDown==1)
            {
                ShutDown=0
                page shutdown
            }
            if(Error==1)
            {
                Error=0
                page ERROR_PAGE
            }
            if(ExternalReset==1)
            {
                ExternalReset=0
                parse.buffer.txt=""
                BufferLen=0
                code_c
                page connect
            }
        
        Touch Release Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn         parseCommon 0
            ///
            /// @brief      Parse buffer using a starting and ending position
            /// @param[in]  parse.search.txt      Text to search for
            /// @param[in]  parse.startPos.val    Starting char postion to search from
            /// @param[out] parse.matched.val     1 if match, 0 if no match
            ///////////////////////////////////////////////////////////////////////////////
            parse.matched.val=0
            parse.eval.txt=parse.buffer.txt
            strlen parse.search.txt,j
            substr parse.eval.txt,parse.result.txt,parse.startPos.val,j
            if(parse.result.txt==parse.search.txt)
            {
                parse.matched.val=1
            }else
            {
                parse.matched.val=0
            }
        
Timer luxRun
    Attributes
        ID         : 18
        Scope      : local
        Period (ms): 100
        Enabled    : yes
    
    Events
        Timer Event
            ///////////////////////////////////////////////////////////////////////////////
            /// @fn luxRun
            /// @breif Main Program Loop
            ///////////////////////////////////////////////////////////////////////////////
            click luxRead,1
            click luxView,1
            click luxController,1
            click luxSend,0
            doevents
        
